<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { size: A4 portrait; margin: 14mm 12mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 4px; text-align: center; text-transform: uppercase; }
        h2 { font-size: 15px; margin: 12px 0 4px; text-align: center; }
        .muted { color: #6b7280; font-size: 11px; }
        .report-header { text-align: center; border-bottom: 1px solid #cbd5e1; padding-bottom: 10px; margin-bottom: 12px; }
        .clinic-logo { max-height: 58px; max-width: 130px; object-fit: contain; margin-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { padding: 5px 7px; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; text-align: left; text-transform: uppercase; font-size: 10px; }
        .amount { text-align: right; }
        .heading td { background: #eef2f7; font-weight: bold; text-transform: uppercase; }
        .total td { font-weight: bold; border-top: 2px solid #9ca3af; }
        .final td { background: #ecfdf3; font-weight: bold; border-top: 2px solid #16a34a; }
        .line-note { color: #6b7280; font-size: 10px; margin-top: 2px; }
        .preview-actions { margin-bottom: 12px; text-align: right; }
        .preview-actions button { padding: 6px 10px; }
        @media print { .preview-actions { display: none; } }
    </style>
</head>
<body>
    @if(!empty($preview))
        <div class="preview-actions">
            <button type="button" onclick="window.print()">Print</button>
        </div>
    @endif

    <div class="report-header">
        @if($clinicSettings->logoDataUri())
            <img src="{{ $clinicSettings->logoDataUri() }}" class="clinic-logo" alt="Clinic Logo">
        @endif
        <h1>{{ $clinicSettings->clinic_name }}</h1>
        <div class="muted">{{ $clinicSettings->clinic_address }}</div>
        <div class="muted">
            @if($clinicSettings->clinic_contact)
                Tel: {{ $clinicSettings->clinic_contact }}
            @endif
            @if($clinicSettings->clinic_email)
                {{ $clinicSettings->clinic_contact ? ' | ' : '' }}Email: {{ $clinicSettings->clinic_email }}
            @endif
        </div>
        <h2>Income Statement</h2>
        <div class="muted">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</div>
        <div class="muted">Generated {{ $generated_at->format('M d, Y h:i A') }}</div>
        <div class="muted">Generated by {{ $generated_by }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th class="amount">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr class="heading"><td>Revenue</td><td class="amount">GH₵ {{ number_format($statement['revenue'], 2) }}</td></tr>
            @foreach($revenue_lines as $line)
                <tr><td>{{ $line['name'] }}</td><td class="amount">GH₵ {{ number_format($line['amount'], 2) }}</td></tr>
            @endforeach

            <tr class="heading"><td>Cost Of Sales</td><td class="amount">GH₵ {{ number_format($statement['cost_of_sales'], 2) }}</td></tr>
            @foreach($cost_lines as $line)
                <tr><td>{{ $line['name'] }}</td><td class="amount">GH₵ {{ number_format($line['amount'], 2) }}</td></tr>
            @endforeach

            <tr class="total"><td>Gross Profit</td><td class="amount">GH₵ {{ number_format($statement['gross_profit'], 2) }}</td></tr>

            <tr class="heading"><td>Operating Expenses</td><td class="amount">GH₵ {{ number_format($statement['operating_expenses'], 2) }}</td></tr>
            @foreach($operating_lines as $line)
                <tr>
                    <td>
                        {{ $line['name'] }}
                        @if(!empty($line['notes']))<div class="line-note">{{ $line['notes'] }}</div>@endif
                    </td>
                    <td class="amount">GH₵ {{ number_format($line['amount'], 2) }}</td>
                </tr>
            @endforeach

            <tr class="total"><td>Operating Profit</td><td class="amount">GH₵ {{ number_format($statement['operating_profit'], 2) }}</td></tr>

            <tr class="heading"><td>Non-operating Expenses</td><td class="amount">GH₵ {{ number_format($statement['non_operating_expenses'], 2) }}</td></tr>
            @foreach($non_operating_lines as $line)
                <tr>
                    <td>
                        {{ $line['name'] }}
                        @if(!empty($line['notes']))<div class="line-note">{{ $line['notes'] }}</div>@endif
                    </td>
                    <td class="amount">GH₵ {{ number_format($line['amount'], 2) }}</td>
                </tr>
            @endforeach

            <tr class="total"><td>Profit For The Period</td><td class="amount">GH₵ {{ number_format($statement['profit_for_period'], 2) }}</td></tr>
            <tr><td>Tax ({{ number_format($statement['tax_rate'], 2) }}%)</td><td class="amount">GH₵ {{ number_format($statement['tax_amount'], 2) }}</td></tr>
            <tr class="final"><td>Net Profit</td><td class="amount">GH₵ {{ number_format($statement['net_profit'], 2) }}</td></tr>
        </tbody>
    </table>
</body>
</html>
