<?php

namespace App\Http\Controllers;

use App\Models\IncomeStatementEntry;
use App\Models\SaleItem;
use App\Models\Setting;
use Carbon\Carbon;
use Illuminate\Http\Request;

class IncomeStatementExportController extends Controller
{
    private const DEFAULT_TEMPLATE_NOTE = 'Default recurring value from income statement setup.';

    public function exportCsv(Request $request)
    {
        return $this->csv($request);
    }

    public function exportPdf(Request $request)
    {
        return $this->pdf($request);
    }

    public function csv(Request $request)
    {
        $report = $this->buildReport($request);
        $filename = 'income-statement-' . $report['from'] . '-to-' . $report['to'] . '.csv';

        return response()->streamDownload(function () use ($report) {
            $file = fopen('php://output', 'w');
            fputcsv($file, ['Income Statement', $report['from'], $report['to']]);
            fputcsv($file, [$report['clinicSettings']->clinic_name]);
            fputcsv($file, [$report['clinicSettings']->clinic_address]);
            fputcsv($file, ['Contact', $report['clinicSettings']->clinic_contact, 'Email', $report['clinicSettings']->clinic_email]);
            fputcsv($file, ['Generated By', $report['generated_by']]);
            fputcsv($file, []);

            $this->writeCsvSection($file, 'Revenue', $report['revenue_lines']);
            fputcsv($file, ['Revenue Total', $report['statement']['revenue']]);
            $this->writeCsvSection($file, 'Cost Of Sales', $report['cost_lines']);
            fputcsv($file, ['Gross Profit', $report['statement']['gross_profit']]);
            $this->writeCsvSection($file, 'Operating Expenses', $report['operating_lines']);
            fputcsv($file, ['Operating Profit', $report['statement']['operating_profit']]);
            $this->writeCsvSection($file, 'Non-operating Expenses', $report['non_operating_lines']);
            fputcsv($file, ['Profit For The Period', $report['statement']['profit_for_period']]);
            fputcsv($file, ['Tax (' . number_format($report['statement']['tax_rate'], 2) . '%)', $report['statement']['tax_amount']]);
            fputcsv($file, ['Net Profit', $report['statement']['net_profit']]);
            fclose($file);
        }, $filename, ['Content-Type' => 'text/csv']);
    }

    public function pdf(Request $request)
    {
        $report = $this->buildReport($request);
        $filename = 'income-statement-' . $report['from'] . '-to-' . $report['to'] . '.pdf';

        return \Barryvdh\DomPDF\Facade\Pdf::loadView('reports.pdf-income-statement', $report)
            ->setPaper('a4', 'portrait')
            ->download($filename);
    }

    public function preview(Request $request)
    {
        return view('reports.pdf-income-statement', $this->buildReport($request) + ['preview' => true]);
    }

    protected function writeCsvSection($file, $title, $lines)
    {
        fputcsv($file, []);
        fputcsv($file, [$title]);

        foreach ($lines as $line) {
            fputcsv($file, [$line['name'], $line['amount'], $line['notes'] ?? '']);
        }
    }

    protected function buildReport(Request $request)
    {
        $from = $this->normalizeDate($request->input('from'), now()->startOfMonth());
        $to = $this->normalizeDate($request->input('to'), now()->endOfMonth());
        $fromCarbon = Carbon::parse($from)->startOfDay();
        $toCarbon = Carbon::parse($to)->endOfDay();

        if ($fromCarbon->gt($toCarbon)) {
            [$fromCarbon, $toCarbon] = [$toCarbon->copy()->startOfDay(), $fromCarbon->copy()->endOfDay()];
            $from = $fromCarbon->toDateString();
            $to = $toCarbon->toDateString();
        }

        $revenueLines = $this->salesLineQuery($fromCarbon, $toCarbon)
            ->selectRaw("COALESCE(categories.name, 'Uncategorized') as name")
            ->selectRaw('SUM(sale_items.subtotal) as amount')
            ->groupBy('categories.id', 'categories.name')
            ->orderBy('name')
            ->get()
            ->map(fn ($line) => ['name' => $line->name, 'amount' => (float) $line->amount]);

        $costLines = $this->salesLineQuery($fromCarbon, $toCarbon)
            ->selectRaw("COALESCE(categories.name, 'Uncategorized') as name")
            ->selectRaw('SUM(sale_items.dispensed_quantity * COALESCE(products.cost_price, 0)) as amount')
            ->groupBy('categories.id', 'categories.name')
            ->orderBy('name')
            ->get()
            ->map(fn ($line) => ['name' => $line->name, 'amount' => (float) $line->amount]);

        $entries = IncomeStatementEntry::with('creator')
            ->where('is_active', true)
            ->whereBetween('entry_date', [$from, $to])
            ->orderBy('entry_date')
            ->orderBy('name')
            ->get();

        $operatingLines = $entries->where('section', IncomeStatementEntry::OPERATING_EXPENSE)
            ->map(fn ($line) => [
                'name' => $line->name,
                'amount' => (float) $line->amount,
                'notes' => $this->exportNote($line->notes),
                'created_by' => $line->creator->name ?? 'System',
            ]);
        $nonOperatingLines = $entries->where('section', IncomeStatementEntry::NON_OPERATING_EXPENSE)
            ->map(fn ($line) => [
                'name' => $line->name,
                'amount' => (float) $line->amount,
                'notes' => $this->exportNote($line->notes),
                'created_by' => $line->creator->name ?? 'System',
            ]);
        $taxEntry = $entries->where('section', IncomeStatementEntry::TAX)->sortByDesc('entry_date')->first();

        $revenue = (float) $revenueLines->sum('amount');
        $costOfSales = (float) $costLines->sum('amount');
        $grossProfit = $revenue - $costOfSales;
        $operatingExpenses = (float) $operatingLines->sum('amount');
        $operatingProfit = $grossProfit - $operatingExpenses;
        $nonOperatingExpenses = (float) $nonOperatingLines->sum('amount');
        $profitForPeriod = $operatingProfit - $nonOperatingExpenses;
        $taxRate = $taxEntry ? (float) $taxEntry->percentage : 0;
        $taxAmount = $profitForPeriod > 0 ? $profitForPeriod * ($taxRate / 100) : 0;

        return [
            'from' => $from,
            'to' => $to,
            'generated_at' => now(),
            'generated_by' => optional($request->user())->name ?? 'System',
            'clinicSettings' => Setting::getSettings(),
            'revenue_lines' => $revenueLines,
            'cost_lines' => $costLines,
            'operating_lines' => $operatingLines,
            'non_operating_lines' => $nonOperatingLines,
            'statement' => [
                'revenue' => $revenue,
                'cost_of_sales' => $costOfSales,
                'gross_profit' => $grossProfit,
                'operating_expenses' => $operatingExpenses,
                'operating_profit' => $operatingProfit,
                'non_operating_expenses' => $nonOperatingExpenses,
                'profit_for_period' => $profitForPeriod,
                'tax_rate' => $taxRate,
                'tax_amount' => $taxAmount,
                'net_profit' => $profitForPeriod - $taxAmount,
            ],
        ];
    }

    protected function normalizeDate($date, $fallback)
    {
        try {
            return Carbon::parse($date ?: $fallback)->format('Y-m-d');
        } catch (\Exception $e) {
            return Carbon::parse($fallback)->format('Y-m-d');
        }
    }

    protected function exportNote($note)
    {
        return trim((string) $note) === self::DEFAULT_TEMPLATE_NOTE ? null : $note;
    }

    protected function salesLineQuery($from, $to)
    {
        return SaleItem::query()
            ->join('sales', 'sale_items.sale_id', '=', 'sales.id')
            ->leftJoin('products', 'sale_items.product_id', '=', 'products.id')
            ->leftJoin('categories', 'products.category_id', '=', 'categories.id')
            ->where('sales.is_refunded', false)
            ->whereBetween('sales.created_at', [$from, $to]);
    }
}
